### ISSUE TITLE
small_clusters dataset crashes the program

### ISSUE THREAD

**Issue by ecalder6** [ebridge2/cs_475_testing#10]
Traceback (most recent call last):
  File "unsupervised_tests.py", line 107, in <module>
    main()
  File "unsupervised_tests.py", line 103, in main
    test.run()
  File "unsupervised_tests.py", line 35, in run
    self.lambda_means()
  File "unsupervised_tests.py", line 62, in lambda_means
    print str(dataset + " | " + acc[:-1] + " | " + nclus[-2] + " | " + "%.4f" % (run_time,) + "(s)")
IndexError: list index out of range

**Comment by ebridge2** [comment]
Small clusters doesn't have a .dev associated; hence it crashes because there are no clusters (so running classify.py is not possible). Updating to remove the small_clusters from the list entirely; I had it in there initially just so I could have the command printed for testing of the small_clusters.train last night, and forgot to remove it when I pushed.

**Comment by ebridge2** [comment]
@199fd9c
